application: site-publish
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/spi/.*
  script: services.app
- url: /_sitepublish/.*
  login: admin
  script: view.app
- url: /.*
  script: view.app

libraries:
- name: webapp2
  version: latest
