application: callisto-v1
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_/content/.*
  script: publish.app
- url: /.*
  script: view.app

libraries:
- name: webapp2
  version: latest
